default: &default
  adapter:  postgresql
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout:  5000
  encoding: utf8

development:
  <<: *default
  database: experiential_learning_platform_development

test:
  <<: *default
  database: experiential_learning_platform_test

dev:
  <<: *default
  database:  <%=ENV['DB_NAME'] %>
  host:      <%=ENV['DB_HOST'] %>
  username:  <%= ENV['DB_USER'] %>
  password:  <%= ENV['DB_PASS'] %>
  port:      <%=ENV['DB_PORT'] %>

qa:
  <<: *default
  database:  <%=ENV['DB_NAME'] %>
  host:      <%=ENV['DB_HOST'] %>
  username:  <%= ENV['DB_USER'] %>
  password:  <%= ENV['DB_PASS'] %>
  port:      <%=ENV['DB_PORT'] %>

staging:
  <<: *default
  database:  <%=ENV['DB_NAME'] %>
  host:      <%=ENV['DB_HOST'] %>
  username:  <%= ENV['DB_USER'] %>
  password:  <%= ENV['DB_PASS'] %>
  port:      <%=ENV['DB_PORT'] %>

production:
  <<: *default
  database:  <%=ENV['DB_NAME'] %>
  host:      <%=ENV['DB_HOST'] %>
  username:  <%= ENV['DB_USER'] %>
  password:  <%= ENV['DB_PASS'] %>
  port:      <%=ENV['DB_PORT'] %>